[workspace]
members = ["rookie-rs", "bindings/python", "bindings/node", "cli"]

exclude = [
  # examples that can be compiled with the tauri CLI
  "examples/*",
]

default-members = ["rookie-rs", "bindings/python"]
resolver = "2"
