[package]
name = "cli"
version = "0.5.2-beta.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
env_logger = { version = "0.11.3", features = ["color"] }
lazy_static = "1.4.0"
rookie = { path = "../rookie-rs" }
serde_json = "1.0.107"
